abstract class ChanagePasswordStates {}

class ChanagePasswordinitialStates extends ChanagePasswordStates{}
class ChanagePasswordLoadingStates extends ChanagePasswordStates{}
class ChanagePasswordSuccsessStates extends ChanagePasswordStates{}
class ChanagePasswordFailedStates extends ChanagePasswordStates{}